[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/xlab/treeprint"
